from api.tests.tests_evaluation import EvaluationTests
from api.tests.tests_user import UserTests
from api.tests.tests_profile import ProfileTests
from api.tests.tests_community import CommunityTests
from api.tests.tests_community_local import LocalCommunityTests
from api.tests.tests_skill_category import SkillCategoryTests
from api.tests.tests_skill import SkillTests
from api.tests.tests_server_actions import AutoCloseTests, CleanPrtTests, ManageReportedObjectsTests
from api.tests.tests_faq import FaqTests
from api.tests.tests_inappropriate import InappropriateTests
from api.tests.tests_suggestion import SuggestionTests
from api.tests.tests_location import LocationTests
from api.tests.tests_location_local import LocationLocalCommunityTests
from api.tests.tests_location_transport import LocationTransportCommunityTests
from api.tests.tests_requests import RequestTests
from api.tests.tests_offer import OfferTests
from api.tests.tests_member import MemberTests
from api.tests.tests_evaluation import EvaluationTests
from api.tests.tests_meeting import MeetingTests
from api.tests.tests_meeting_point import MeetingPointTests
from api.tests.tests_message import MessageTests
from api.tests.tests_text import TextTests