image: smartribe/test-python34:0.4

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test
  - /etc/init.d/docker.io start
  - sleep 5
  - docker.io build --tag=docker.eip.infoclip.fr:5000/api:${DRONE_COMMIT:35} .
  - docker.io push docker.eip.infoclip.fr:5000/api:${DRONE_COMMIT:35}
  - /etc/init.d/docker.io stop
  - echo "Build Finished"
  - sleep 5

notify:
  email:
    recipients:
      - coleu_y@etna-alternance.net
      - bordie_r@etna-alternance.net
