image: smartribe/test-python34:0.5

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test

publish:
  docker:
      docker_host: tcp://ci.smartribe.fr:10000
      docker_version: 1.0.1
      registry_protocol: https
      image_name: "docker.smartribe.fr:443/api"

notify:
  email:
    recipients:
      - coleu_y@etna-alternance.net
      - bordie_r@etna-alternance.net
      - delabr_e@etna-alternance.net
  slack:
      - webhook_url: 'https://hooks.slack.com/services/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'
      - channel: '#api'
      - username: 'drone'
      - on_started: true
      - on_success: true
      - on_failure: true
