image: smartribe/test-python34:0.4

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test
  - docker -d --dns 8.8.8.8 --dns 8.8.4.4 --insecure-registry docker.eip.infoclip.fr:5000 &
  - sleep 5
  - docker build --tag=docker.eip.infoclip.fr:5000/api:${DRONE_COMMIT:35} .
  - docker push docker.eip.infoclip.fr:5000/api:${DRONE_COMMIT:35}
  - killall docker
  - echo "Build Finished"
  - sleep 5

notify:
  email:
    recipients:
      - coleu_y@etna-alternance.net
      - bordie_r@etna-alternance.net
