image: smartribe/test-python34:0.5

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test

publish:
  docker:
      docker_host: tcp://ci.smartribe.fr:10000
      docker_version: 1.0.1
      registry_protocol: https
      image_name: "docker.smartribe.fr:443/api"

notify:
  email:
    recipients:
      - coleu_y@etna-alternance.net
      - bordie_r@etna-alternance.net
