image: smartribe/test-python34:0.5

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test

notify:
  email:
    recipients:
      - coleu_y@etna-alternance.net
      - bordie_r@etna-alternance.net
