image: smartribe/test-python34:0.5

script:
  - pip3 install -r requirements.txt 
  - python3 manage.py migrate
  - python3 manage.py test

publish:
  docker:
      docker_host: tcp://ci.eip.infoclip.fr:10000
      docker_version: 1.0.1
      registry_protocol: https
      image_name: docker.eip.infoclip.fr:443/api
      registry_login: true
      username: "smartribe"
      password: "totoro"

notify:
  email:
    recipients:
      - y@nn-col.eu
      - bordie_r@etna-alternance.net
