FORMAT: 1A
HOST: http://www.google.com

# smartribe
Official documentation API v1.
url: https://api.smatri.be/api/v1/

# Group Users
User actions

## Users Unauthenticated actions [/users]
### Create user [POST]

Once the user is succesfully created, an email is
sent back to validate the authenticity of the
email address. The email contains a link to the website
address with a token in the url.

+ Request (application/json)

        { 
            "username": "toto",
            "email": "toto@test.com",
            "password": "strongpassword"
        }

+ Response 201 (application/json)

        {
            "id": "1",
            "username": "toto",
            "email": "toto@test.com",
            "groups": [],
            "is_active": false
        }


## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
